"""
ruby Project (Generated by Panther on 2023-10-02)
"""

from datetime import timedelta
from pathlib import Path

from panther.throttling import Throttling
from panther.utils import load_env

BASE_DIR = Path(__name__).resolve().parent
env = load_env(BASE_DIR / '.env')

SECRET_KEY = env['SECRET_KEY']
OTP_EXP_SECOND = 120
OTP_LEN = 4

MIDDLEWARES = [
    ('panther.middlewares.db.DatabaseMiddleware', {'url': f'pantherdb://{BASE_DIR}/database.pdb'}),
    ('panther.middlewares.redis.RedisMiddleware', {'host': '127.0.0.1', 'port': 6379}),
]

USER_MODEL = 'user.models.User'

AUTHENTICATION = 'panther.authentications.JWTAuthentication'

JWTConfig = {
    'life_time': timedelta(days=1),
    'refresh_life_time': timedelta(days=2)
}

MONITORING = True
LOG_QUERIES = True

THROTTLING = Throttling(rate=60, duration=timedelta(minutes=1))

URLs = 'core.urls.url_routing'
